version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-entidades
    environment:
      - POSTGRES_USER=diego
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=aviones
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data: